name: Build & Release

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.5.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Release
        uses: HSGamer/action-mcreleaser@main
        with:
          files: |
            **/target/topper-*-shaded.jar
            **/target/topper-*-@(sources|javadoc).jar
        env:
          DESCRIPTION: ${{ steps.changelog.outputs.changelog }}
          GAME_VERSIONS: "1.8..latest"

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT: 6zYtBRSV
          MODRINTH_LOADERS: |
            bukkit
            spigot
            paper
            purpur
            folia

          POLYMART_KEY: ${{ secrets.POLYMART_KEY }}
          POLYMART_RESOURCE: 7111
